### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ZMQ Request timeout.

### ISSUE THREAD

**Issue by cybermizrach** [BonneVoyager/node-mt4-zmq-bridge#8]
Hi @BonneVoyager,

I was testing this EA v1.2.0 and library but I encountered an error below. 

**Code**
```
 	mt4.getAccountInfo().then((account) => {
		console.log(account);
	});
    mt4.getLastCandles("BTCUSD").then((candles) => {
		console.log(candles);
	});
```

**Error**

```
(node:24816) UnhandledPromiseRejectionWarning: Error: ZMQ Request timeout.
    at Timeout._onTimeout (D:\OneDrive\Github\MT4V1\node_modules\metatrader4\build\MetaTrader4Connection.js:178:44)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async 
function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:24816) UnhandledPromiseRejectionWarning: Error: ZMQ Request timeout.
    at Timeout._onTimeout (D:\OneDrive\Github\MT4V1\node_modules\metatrader4\build\MetaTrader4Connection.js:178:44)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(node:24816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async 
function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**MT4 LOG**

```
2021.06.27 01:31:25.504	MetaTrader4Bridge BTCUSD,M1: Parsing: CHANGEME|1|41
2021.06.27 01:31:25.504	MetaTrader4Bridge BTCUSD,M1: Response: 1|0|USD|46805.53|0.00|46805.53|0.00|46805.53|0.00|50.00|30.00
2021.06.27 01:31:25.520	MetaTrader4Bridge BTCUSD,M1: Parsing: CHANGEME|2|71|BTCUSD
2021.06.27 01:31:25.520	MetaTrader4Bridge BTCUSD,M1: Response: 2|
```

It looks like the response did not reach the Node JS.

Thank you in advance for your help.

**Comment by cybermizrach** [comment]
I was using the library in https://github.com/peterszombati/metatrader4.

But when I  used the node-mt4-zmq-bridge, it worked.  Therefore, the problem is in the other library. I'm closing this issue.
